export const COLORS = [
  "gray",
  "mauve",
  "slate",
  "sage",
  "olive",
  "sand",
  "tomato",
  "red",
  "ruby",
  "crimson",
  "pink",
  "plum",
  "purple",
  "violet",
  "iris",
  "indigo",
  "blue",
  "cyan",
  "teal",
  "jade",
  "green",
  "grass",
  "brown",
  "bronze",
  "gold",
  "sky",
  "mint",
  "lime",
  "yellow",
  "amber",
  "orange",
] as const;

export const COMPANIES = [
  { value: "Amd", label: "Amd" },
  { value: "Aqr Capital Management", label: "Aqr Capital Management" },
  { value: "Accenture", label: "Accenture" },
  { value: "Accolite", label: "Accolite" },
  { value: "Acko", label: "Acko" },
  { value: "Activision", label: "Activision" },
  { value: "Adobe", label: "Adobe" },
  { value: "Affirm", label: "Affirm" },
  { value: "Agoda", label: "Agoda" },
  { value: "Airbnb", label: "Airbnb" },
  { value: "Airbus Se", label: "Airbus Se" },
  { value: "Airtel", label: "Airtel" },
  { value: "Airwallex", label: "Airwallex" },
  { value: "Akamai", label: "Akamai" },
  { value: "Akuna Capital", label: "Akuna Capital" },
  { value: "Alibaba", label: "Alibaba" },
  { value: "Altimetrik", label: "Altimetrik" },
  { value: "Amadeus", label: "Amadeus" },
  { value: "Amazon", label: "Amazon" },
  { value: "Amdocs", label: "Amdocs" },
  { value: "American Express", label: "American Express" },
  { value: "Analytics Quotient", label: "Analytics Quotient" },
  { value: "Anduril", label: "Anduril" },
  { value: "Aon", label: "Aon" },
  { value: "Apollo.Io", label: "Apollo.Io" },
  { value: "Appdynamics", label: "Appdynamics" },
  { value: "Appfolio", label: "Appfolio" },
  { value: "Apple", label: "Apple" },
  { value: "Applied Intuition", label: "Applied Intuition" },
  { value: "Arcesium", label: "Arcesium" },
  { value: "Arista Networks", label: "Arista Networks" },
  { value: "Asana", label: "Asana" },
  { value: "Atlassian", label: "Atlassian" },
  { value: "Attentive", label: "Attentive" },
  { value: "Audible", label: "Audible" },
  { value: "Aurora", label: "Aurora" },
  { value: "Autodesk", label: "Autodesk" },
  { value: "Avalara", label: "Avalara" },
  { value: "Avito", label: "Avito" },
  { value: "Axon", label: "Axon" },
  { value: "Bill Holdings", label: "Bill Holdings" },
  { value: "Bny Mellon", label: "Bny Mellon" },
  { value: "Bp", label: "Bp" },
  { value: "Baidu", label: "Baidu" },
  { value: "Bank Of America", label: "Bank Of America" },
  { value: "Barclays", label: "Barclays" },
  { value: "Bentley Systems", label: "Bentley Systems" },
  { value: "Bharatpe", label: "Bharatpe" },
  { value: "Bitgo", label: "Bitgo" },
  { value: "Blackrock", label: "Blackrock" },
  { value: "Blackstone", label: "Blackstone" },
  { value: "Blizzard", label: "Blizzard" },
  { value: "Block", label: "Block" },
  { value: "Bloomberg", label: "Bloomberg" },
  { value: "Bolt", label: "Bolt" },
  { value: "Booking.Com", label: "Booking.Com" },
  { value: "Bosch", label: "Bosch" },
  { value: "Box", label: "Box" },
  { value: "Braze", label: "Braze" },
  { value: "Brex", label: "Brex" },
  { value: "Bridgewater Associates", label: "Bridgewater Associates" },
  { value: "Bytedance", label: "Bytedance" },
  { value: "Cars24", label: "Cars24" },
  { value: "Cedcoss", label: "Cedcoss" },
  { value: "Cme Group", label: "Cme Group" },
  { value: "Cred", label: "Cred" },
  { value: "Ctc", label: "Ctc" },
  { value: "Cvent", label: "Cvent" },
  { value: "Cadence", label: "Cadence" },
  { value: "Canonical", label: "Canonical" },
  { value: "Capgemini", label: "Capgemini" },
  { value: "Capital One", label: "Capital One" },
  { value: "Careem", label: "Careem" },
  { value: "Cashfree", label: "Cashfree" },
  { value: "Celigo", label: "Celigo" },
  { value: "Chewy", label: "Chewy" },
  { value: "Chime", label: "Chime" },
  { value: "Circle", label: "Circle" },
  { value: "Cisco", label: "Cisco" },
  { value: "Citadel", label: "Citadel" },
  { value: "Citigroup", label: "Citigroup" },
  { value: "Citrix", label: "Citrix" },
  { value: "Clari", label: "Clari" },
  { value: "Cleartrip", label: "Cleartrip" },
  { value: "Cloudera", label: "Cloudera" },
  { value: "Cloudflare", label: "Cloudflare" },
  { value: "Cognizant", label: "Cognizant" },
  { value: "Cohesity", label: "Cohesity" },
  { value: "Coinbase", label: "Coinbase" },
  { value: "Comcast", label: "Comcast" },
  { value: "Commvault", label: "Commvault" },
  { value: "Compass", label: "Compass" },
  { value: "Confluent", label: "Confluent" },
  { value: "Consultadd", label: "Consultadd" },
  { value: "Coupang", label: "Coupang" },
  { value: "Coursera", label: "Coursera" },
  { value: "Coveo", label: "Coveo" },
  { value: "Credit Karma", label: "Credit Karma" },
  { value: "Criteo", label: "Criteo" },
  { value: "Crowdstrike", label: "Crowdstrike" },
  { value: "Cruise", label: "Cruise" },
  { value: "Curefit", label: "Curefit" },
  { value: "De Shaw", label: "De Shaw" },
  { value: "Dp World", label: "Dp World" },
  { value: "Drw", label: "Drw" },
  { value: "Dxc Technology", label: "Dxc Technology" },
  { value: "Darwinbox", label: "Darwinbox" },
  { value: "Databricks", label: "Databricks" },
  { value: "Datadog", label: "Datadog" },
  { value: "Dataminr", label: "Dataminr" },
  { value: "Delhivery", label: "Delhivery" },
  { value: "Deliveroo", label: "Deliveroo" },
  { value: "Dell", label: "Dell" },
  { value: "Deloitte", label: "Deloitte" },
  { value: "Deltax", label: "Deltax" },
  { value: "Deutsche Bank", label: "Deutsche Bank" },
  { value: "Devrev", label: "Devrev" },
  { value: "Devsinc", label: "Devsinc" },
  { value: "Devtron", label: "Devtron" },
  { value: "Directi", label: "Directi" },
  { value: "Disney", label: "Disney" },
  { value: "Docusign", label: "Docusign" },
  { value: "Doordash", label: "Doordash" },
  { value: "Dream11", label: "Dream11" },
  { value: "Dropbox", label: "Dropbox" },
  { value: "Druva", label: "Druva" },
  { value: "Dunzo", label: "Dunzo" },
  { value: "Duolingo", label: "Duolingo" },
  { value: "Epam Systems", label: "Epam Systems" },
  { value: "Ey", label: "Ey" },
  { value: "Earnin", label: "Earnin" },
  { value: "Edelweiss Group", label: "Edelweiss Group" },
  { value: "Electronic Arts", label: "Electronic Arts" },
  { value: "Epic Systems", label: "Epic Systems" },
  { value: "Expedia", label: "Expedia" },
  { value: "Fpt", label: "Fpt" },
  { value: "Factset", label: "Factset" },
  { value: "Faire", label: "Faire" },
  { value: "Fastenal", label: "Fastenal" },
  { value: "Fidelity", label: "Fidelity" },
  { value: "Fiverr", label: "Fiverr" },
  { value: "Flexera", label: "Flexera" },
  { value: "Flexport", label: "Flexport" },
  { value: "Flipkart", label: "Flipkart" },
  { value: "Fortinet", label: "Fortinet" },
  { value: "Freecharge", label: "Freecharge" },
  { value: "Freshworks", label: "Freshworks" },
  { value: "Ge Digital", label: "Ge Digital" },
  { value: "Ge Healthcare", label: "Ge Healthcare" },
  { value: "Gsa Capital", label: "Gsa Capital" },
  { value: "Gsn Games", label: "Gsn Games" },
  { value: "Gameskraft", label: "Gameskraft" },
  { value: "Garmin", label: "Garmin" },
  { value: "Geico", label: "Geico" },
  { value: "General Motors", label: "General Motors" },
  { value: "Genpact", label: "Genpact" },
  { value: "Godaddy", label: "Godaddy" },
  { value: "Gojek", label: "Gojek" },
  { value: "Goldman Sachs", label: "Goldman Sachs" },
  { value: "Google", label: "Google" },
  { value: "Grab", label: "Grab" },
  { value: "Grammarly", label: "Grammarly" },
  { value: "Graviton", label: "Graviton" },
  { value: "Groupon", label: "Groupon" },
  { value: "Groww", label: "Groww" },
  { value: "Grubhub", label: "Grubhub" },
  { value: "Guidewire", label: "Guidewire" },
  { value: "Gusto", label: "Gusto" },
  { value: "Hcl", label: "Hcl" },
  { value: "Hp", label: "Hp" },
  { value: "Hpe", label: "Hpe" },
  { value: "Hsbc", label: "Hsbc" },
  { value: "Harness", label: "Harness" },
  { value: "Hashedin", label: "Hashedin" },
  { value: "Hertz", label: "Hertz" },
  { value: "Hilabs", label: "Hilabs" },
  { value: "Highspot", label: "Highspot" },
  { value: "Hive", label: "Hive" },
  { value: "Hiver", label: "Hiver" },
  { value: "Honeywell", label: "Honeywell" },
  { value: "Hotstar", label: "Hotstar" },
  { value: "Houzz", label: "Houzz" },
  { value: "Huawei", label: "Huawei" },
  { value: "Hubspot", label: "Hubspot" },
  { value: "Hudson River Trading", label: "Hudson River Trading" },
  { value: "Hulu", label: "Hulu" },
  { value: "Ibm", label: "Ibm" },
  { value: "Iit Bombay", label: "Iit Bombay" },
  { value: "Imc", label: "Imc" },
  { value: "Indmoney", label: "Indmoney" },
  { value: "Ivp", label: "Ivp" },
  { value: "Ixl", label: "Ixl" },
  { value: "Inmobi", label: "Inmobi" },
  { value: "Indeed", label: "Indeed" },
  { value: "Info Edge", label: "Info Edge" },
  { value: "Informatica", label: "Informatica" },
  { value: "Infosys", label: "Infosys" },
  { value: "Instacart", label: "Instacart" },
  { value: "Intel", label: "Intel" },
  { value: "Intuit", label: "Intuit" },
  { value: "J.P. Morgan", label: "J.P. Morgan" },
  { value: "Jane Street", label: "Jane Street" },
  { value: "Jump Trading", label: "Jump Trading" },
  { value: "Juniper Networks", label: "Juniper Networks" },
  { value: "Juspay", label: "Juspay" },
  { value: "Kla", label: "Kla" },
  { value: "Kakao", label: "Kakao" },
  { value: "Karat", label: "Karat" },
  { value: "Komprise", label: "Komprise" },
  { value: "Line", label: "Line" },
  { value: "Lti", label: "Lti" },
  { value: "Larsen & Toubro", label: "Larsen & Toubro" },
  { value: "Lendingkart Technologies", label: "Lendingkart Technologies" },
  { value: "Lenskart", label: "Lenskart" },
  { value: "Licious", label: "Licious" },
  { value: "Liftoff", label: "Liftoff" },
  { value: "Linkedin", label: "Linkedin" },
  { value: "Liveramp", label: "Liveramp" },
  { value: "Lowe'S", label: "Lowe'S" },
  { value: "Lucid", label: "Lucid" },
  { value: "Luxoft", label: "Luxoft" },
  { value: "Lyft", label: "Lyft" },
  { value: "Maq Software", label: "Maq Software" },
  { value: "Msci", label: "Msci" },
  { value: "Machine Zone", label: "Machine Zone" },
  { value: "Makemytrip", label: "Makemytrip" },
  { value: "Mapbox", label: "Mapbox" },
  { value: "Mastercard", label: "Mastercard" },
  { value: "Mathworks", label: "Mathworks" },
  { value: "Mckinsey", label: "Mckinsey" },
  { value: "Media.Net", label: "Media.Net" },
  { value: "Meesho", label: "Meesho" },
  { value: "Mercari", label: "Mercari" },
  { value: "Meta", label: "Meta" },
  { value: "Microsoft", label: "Microsoft" },
  { value: "Microstrategy", label: "Microstrategy" },
  { value: "Millennium", label: "Millennium" },
  { value: "Mindtree", label: "Mindtree" },
  { value: "Mindtickle", label: "Mindtickle" },
  { value: "Miro", label: "Miro" },
  { value: "Mitsogo", label: "Mitsogo" },
  { value: "Mixpanel", label: "Mixpanel" },
  { value: "Mobileye", label: "Mobileye" },
  { value: "Moengage", label: "Moengage" },
  { value: "Moloco", label: "Moloco" },
  { value: "Mongodb", label: "Mongodb" },
  { value: "Morgan Stanley", label: "Morgan Stanley" },
  { value: "Mountblue", label: "Mountblue" },
  { value: "Moveworks", label: "Moveworks" },
  { value: "Myntra", label: "Myntra" },
  { value: "Ncr", label: "Ncr" },
  { value: "Nagarro", label: "Nagarro" },
  { value: "National Instruments", label: "National Instruments" },
  {
    value: "National Payments Corporation Of India",
    label: "National Payments Corporation Of India",
  },
  { value: "Navan", label: "Navan" },
  { value: "Navi", label: "Navi" },
  { value: "Netapp", label: "Netapp" },
  { value: "Netease", label: "Netease" },
  { value: "Netflix", label: "Netflix" },
  { value: "Netskope", label: "Netskope" },
  { value: "Netsuite", label: "Netsuite" },
  { value: "Nextdoor", label: "Nextdoor" },
  { value: "Niantic", label: "Niantic" },
  { value: "Nielsen", label: "Nielsen" },
  { value: "Nike", label: "Nike" },
  { value: "Ninjacart", label: "Ninjacart" },
  { value: "Nokia", label: "Nokia" },
  { value: "Nordstrom", label: "Nordstrom" },
  { value: "Notion", label: "Notion" },
  { value: "Nuro", label: "Nuro" },
  { value: "Nutanix", label: "Nutanix" },
  { value: "Nvidia", label: "Nvidia" },
  { value: "Nykaa", label: "Nykaa" },
  { value: "Okx", label: "Okx" },
  { value: "Odoo", label: "Odoo" },
  { value: "Okta", label: "Okta" },
  { value: "Ola Cabs", label: "Ola Cabs" },
  { value: "Openai", label: "Openai" },
  { value: "Opendoor", label: "Opendoor" },
  { value: "Optiver", label: "Optiver" },
  { value: "Optum", label: "Optum" },
  { value: "Oracle", label: "Oracle" },
  { value: "Otter.Ai", label: "Otter.Ai" },
  { value: "Ozon", label: "Ozon" },
  { value: "Palantir Technologies", label: "Palantir Technologies" },
  { value: "Palo Alto Networks", label: "Palo Alto Networks" },
  { value: "Patreon", label: "Patreon" },
  { value: "Paypal", label: "Paypal" },
  { value: "Paypay", label: "Paypay" },
  { value: "Payu", label: "Payu" },
  { value: "Paycom", label: "Paycom" },
  { value: "Paytm", label: "Paytm" },
  { value: "Peloton", label: "Peloton" },
  { value: "Phonepe", label: "Phonepe" },
  { value: "Pinterest", label: "Pinterest" },
  { value: "Pocket Gems", label: "Pocket Gems" },
  { value: "Point72", label: "Point72" },
  { value: "Pony.Ai", label: "Pony.Ai" },
  { value: "Pornhub", label: "Pornhub" },
  { value: "Poshmark", label: "Poshmark" },
  { value: "Postmates", label: "Postmates" },
  { value: "Pubmatic", label: "Pubmatic" },
  { value: "Publicis Sapient", label: "Publicis Sapient" },
  { value: "Pure Storage", label: "Pure Storage" },
  { value: "Pwc", label: "Pwc" },
  { value: "Qburst", label: "Qburst" },
  { value: "Qualcomm", label: "Qualcomm" },
  { value: "Qualtrics", label: "Qualtrics" },
  { value: "Quora", label: "Quora" },
  { value: "Rbc", label: "Rbc" },
  { value: "Rakuten", label: "Rakuten" },
  { value: "Reddit", label: "Reddit" },
  { value: "Remitly", label: "Remitly" },
  { value: "Revolut", label: "Revolut" },
  { value: "Riot Games", label: "Riot Games" },
  { value: "Ripple", label: "Ripple" },
  { value: "Rippling", label: "Rippling" },
  { value: "Rivian", label: "Rivian" },
  { value: "Robinhood", label: "Robinhood" },
  { value: "Roblox", label: "Roblox" },
  { value: "Roche", label: "Roche" },
  { value: "Rokt", label: "Rokt" },
  { value: "Roku", label: "Roku" },
  { value: "Rubrik", label: "Rubrik" },
  { value: "Sap", label: "Sap" },
  { value: "Sig", label: "Sig" },
  { value: "Soti", label: "Soti" },
  { value: "Salesforce", label: "Salesforce" },
  { value: "Samsara", label: "Samsara" },
  { value: "Samsung", label: "Samsung" },
  { value: "Scale Ai", label: "Scale Ai" },
  { value: "Sentry", label: "Sentry" },
  { value: "Servicenow", label: "Servicenow" },
  { value: "Sharechat", label: "Sharechat" },
  { value: "Shopee", label: "Shopee" },
  { value: "Shopify", label: "Shopify" },
  { value: "Siemens", label: "Siemens" },
  { value: "Sigmoid", label: "Sigmoid" },
  { value: "Slice", label: "Slice" },
  { value: "Smartsheet", label: "Smartsheet" },
  { value: "Snap", label: "Snap" },
  { value: "Snapdeal", label: "Snapdeal" },
  { value: "Snowflake", label: "Snowflake" },
  { value: "Sofi", label: "Sofi" },
  { value: "Societe Generale", label: "Societe Generale" },
  { value: "Softwire", label: "Softwire" },
  { value: "Sony", label: "Sony" },
  { value: "Soundhound", label: "Soundhound" },
  { value: "Splunk", label: "Splunk" },
  { value: "Spotify", label: "Spotify" },
  { value: "Sprinklr", label: "Sprinklr" },
  { value: "Squarepoint Capital", label: "Squarepoint Capital" },
  { value: "Squarespace", label: "Squarespace" },
  { value: "Stackadapt", label: "Stackadapt" },
  { value: "Stackline", label: "Stackline" },
  { value: "Stripe", label: "Stripe" },
  { value: "Sumo Logic", label: "Sumo Logic" },
  { value: "Swiggy", label: "Swiggy" },
  { value: "Synopsys", label: "Synopsys" },
  { value: "Tanium", label: "Tanium" },
  { value: "Target", label: "Target" },
  { value: "Tech Mahindra", label: "Tech Mahindra" },
  { value: "Tejas Networks", label: "Tejas Networks" },
  { value: "Tekion", label: "Tekion" },
  { value: "Tencent", label: "Tencent" },
  { value: "Teradata", label: "Teradata" },
  { value: "Tesco", label: "Tesco" },
  { value: "Tesla", label: "Tesla" },
  { value: "Texas Instruments", label: "Texas Instruments" },
  { value: "The Trade Desk", label: "The Trade Desk" },
  { value: "Thomson Reuters", label: "Thomson Reuters" },
  { value: "Thoughtworks", label: "Thoughtworks" },
  { value: "Thousandeyes", label: "Thousandeyes" },
  { value: "Tiger Analytics", label: "Tiger Analytics" },
  { value: "Tiktok", label: "Tiktok" },
  { value: "Tinder", label: "Tinder" },
  { value: "Tinkoff", label: "Tinkoff" },
  { value: "Toast", label: "Toast" },
  { value: "Toptal", label: "Toptal" },
  { value: "Tower Research Capital", label: "Tower Research Capital" },
  { value: "Trexquant", label: "Trexquant" },
  { value: "Trilogy", label: "Trilogy" },
  { value: "Tripadvisor", label: "Tripadvisor" },
  { value: "Tusimple", label: "Tusimple" },
  { value: "Turing", label: "Turing" },
  { value: "Turo", label: "Turo" },
  { value: "Turvo", label: "Turvo" },
  { value: "Twilio", label: "Twilio" },
  { value: "Twitch", label: "Twitch" },
  { value: "Two Sigma", label: "Two Sigma" },
  { value: "Ubs", label: "Ubs" },
  { value: "Ukg", label: "Ukg" },
  { value: "Usaa", label: "Usaa" },
  { value: "Uber", label: "Uber" },
  { value: "Uipath", label: "Uipath" },
  { value: "Unity", label: "Unity" },
  { value: "Upstart", label: "Upstart" },
  { value: "Urban Company", label: "Urban Company" },
  { value: "Vk", label: "Vk" },
  { value: "Vmware", label: "Vmware" },
  { value: "Valve", label: "Valve" },
  { value: "Vanguard", label: "Vanguard" },
  { value: "Veeva Systems", label: "Veeva Systems" },
  { value: "Verily", label: "Verily" },
  { value: "Veritas", label: "Veritas" },
  { value: "Verkada", label: "Verkada" },
  { value: "Vimeo", label: "Vimeo" },
  { value: "Virtu Financial", label: "Virtu Financial" },
  { value: "Virtusa", label: "Virtusa" },
  { value: "Visa", label: "Visa" },
  { value: "Walmart Labs", label: "Walmart Labs" },
  { value: "Warnermedia", label: "Warnermedia" },
  { value: "Watchguard", label: "Watchguard" },
  { value: "Wayfair", label: "Wayfair" },
  { value: "Waymo", label: "Waymo" },
  { value: "Weride", label: "Weride" },
  { value: "Wealthfront", label: "Wealthfront" },
  { value: "Wells Fargo", label: "Wells Fargo" },
  { value: "Western Digital", label: "Western Digital" },
  { value: "Whatnot", label: "Whatnot" },
  { value: "Winzo", label: "Winzo" },
  { value: "Wipro", label: "Wipro" },
  { value: "Wise", label: "Wise" },
  { value: "Wish", label: "Wish" },
  { value: "Wissen Technology", label: "Wissen Technology" },
  { value: "Wix", label: "Wix" },
  { value: "Workday", label: "Workday" },
  { value: "Works Applications", label: "Works Applications" },
  { value: "Worldquant", label: "Worldquant" },
  { value: "X", label: "X" },
  { value: "Yahoo", label: "Yahoo" },
  { value: "Yandex", label: "Yandex" },
  { value: "Yelp", label: "Yelp" },
  { value: "Yext", label: "Yext" },
  { value: "Zs Associates", label: "Zs Associates" },
  { value: "Zscaler", label: "Zscaler" },
  { value: "Zalando", label: "Zalando" },
  { value: "Zendesk", label: "Zendesk" },
  { value: "Zenefits", label: "Zenefits" },
  { value: "Zepto", label: "Zepto" },
  { value: "Zeta", label: "Zeta" },
  { value: "Zillow", label: "Zillow" },
  { value: "Ziprecruiter", label: "Ziprecruiter" },
  { value: "Zluri", label: "Zluri" },
  { value: "Zoho", label: "Zoho" },
  { value: "Zomato", label: "Zomato" },
  { value: "Zoom", label: "Zoom" },
  { value: "Zoox", label: "Zoox" },
  { value: "Zopsmart", label: "Zopsmart" },
  { value: "Zynga", label: "Zynga" },
  { value: "Athenahealth", label: "Athenahealth" },
  { value: "Blinkit", label: "Blinkit" },
  { value: "Carwale", label: "Carwale" },
  { value: "Ciena", label: "Ciena" },
  { value: "Ebay", label: "Ebay" },
  { value: "Fourkites", label: "Fourkites" },
  { value: "Instabase", label: "Instabase" },
  { value: "Jio", label: "Jio" },
  { value: "Josh Technology", label: "Josh Technology" },
  { value: "Opentext", label: "Opentext" },
  { value: "Oyo", label: "Oyo" },
  { value: "Peak6", label: "Peak6" },
  { value: "Persistent Systems", label: "Persistent Systems" },
  { value: "Razorpay", label: "Razorpay" },
  { value: "Redbus", label: "Redbus" },
  { value: "Smartnews", label: "Smartnews" },
  { value: "Tcs", label: "Tcs" },
  { value: "Thoughtspot", label: "Thoughtspot" },
  { value: "Zeta Suite", label: "Zeta Suite" },
];

export const TOPICS = [
  { value: "Array", label: "Array" },
  { value: "Backtracking", label: "Backtracking" },
  { value: "Biconnected Component", label: "Biconnected Component" },
  { value: "Binary Indexed Tree", label: "Binary Indexed Tree" },
  { value: "Binary Search", label: "Binary Search" },
  { value: "Binary Search Tree", label: "Binary Search Tree" },
  { value: "Binary Tree", label: "Binary Tree" },
  { value: "Bit Manipulation", label: "Bit Manipulation" },
  { value: "Bitmask", label: "Bitmask" },
  { value: "Brainteaser", label: "Brainteaser" },
  { value: "Breadth-First Search", label: "Breadth-First Search" },
  { value: "Bucket Sort", label: "Bucket Sort" },
  { value: "Combinatorics", label: "Combinatorics" },
  { value: "Concurrency", label: "Concurrency" },
  { value: "Counting", label: "Counting" },
  { value: "Counting Sort", label: "Counting Sort" },
  { value: "Data Stream", label: "Data Stream" },
  { value: "Database", label: "Database" },
  { value: "Depth-First Search", label: "Depth-First Search" },
  { value: "Design", label: "Design" },
  { value: "Divide And Conquer", label: "Divide And Conquer" },
  { value: "Doubly-Linked List", label: "Doubly-Linked List" },
  { value: "Dynamic Programming", label: "Dynamic Programming" },
  { value: "Enumeration", label: "Enumeration" },
  { value: "Eulerian Circuit", label: "Eulerian Circuit" },
  { value: "Game Theory", label: "Game Theory" },
  { value: "Geometry", label: "Geometry" },
  { value: "Graph", label: "Graph" },
  { value: "Greedy", label: "Greedy" },
  { value: "Hash Function", label: "Hash Function" },
  { value: "Hash Table", label: "Hash Table" },
  { value: "Heap (Priority Queue)", label: "Heap (Priority Queue)" },
  { value: "Interactive", label: "Interactive" },
  { value: "Iterator", label: "Iterator" },
  { value: "Line Sweep", label: "Line Sweep" },
  { value: "Linked List", label: "Linked List" },
  { value: "Math", label: "Math" },
  { value: "Matrix", label: "Matrix" },
  { value: "Memoization", label: "Memoization" },
  { value: "Merge Sort", label: "Merge Sort" },
  { value: "Minimum Spanning Tree", label: "Minimum Spanning Tree" },
  { value: "Monotonic Queue", label: "Monotonic Queue" },
  { value: "Monotonic Stack", label: "Monotonic Stack" },
  { value: "Number Theory", label: "Number Theory" },
  { value: "Ordered Set", label: "Ordered Set" },
  { value: "Prefix Sum", label: "Prefix Sum" },
  { value: "Probability And Statistics", label: "Probability And Statistics" },
  { value: "Queue", label: "Queue" },
  { value: "Quickselect", label: "Quickselect" },
  { value: "Radix Sort", label: "Radix Sort" },
  { value: "Randomized", label: "Randomized" },
  { value: "Recursion", label: "Recursion" },
  { value: "Rejection Sampling", label: "Rejection Sampling" },
  { value: "Reservoir Sampling", label: "Reservoir Sampling" },
  { value: "Rolling Hash", label: "Rolling Hash" },
  { value: "Segment Tree", label: "Segment Tree" },
  { value: "Shell", label: "Shell" },
  { value: "Shortest Path", label: "Shortest Path" },
  { value: "Simulation", label: "Simulation" },
  { value: "Sliding Window", label: "Sliding Window" },
  { value: "Sorting", label: "Sorting" },
  { value: "Stack", label: "Stack" },
  { value: "String", label: "String" },
  { value: "String Matching", label: "String Matching" },
  {
    value: "Strongly Connected Component",
    label: "Strongly Connected Component",
  },
  { value: "Suffix Array", label: "Suffix Array" },
  { value: "Topological Sort", label: "Topological Sort" },
  { value: "Tree", label: "Tree" },
  { value: "Trie", label: "Trie" },
  { value: "Two Pointers", label: "Two Pointers" },
  { value: "Union Find", label: "Union Find" },
];
