export const runtime = "edge";

import { AppSidebar } from "@/components/app-sidebar";
import Providers from "@/components/providers/providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <Providers>
          <div className="flex h-screen w-full">
            <AppSidebar />
            <main className="flex-1 overflow-auto">
              <div>
                {/* Header */}
                <div className="flex items-center justify-between">
                  <div className="p-4">
                    <h1 className="text-2xl md:text-3xl font-bold tracking-tight">
                      LeetCode Problems
                    </h1>
                    <p className="text-sm md:text-base text-muted-foreground">
                      Browse and filter problems by company, difficulty, and
                      topics
                    </p>
                  </div>
                </div>

                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
